name: Feature Request
description: Propose a new feature or enhancement for XRootD.
body:
- type: markdown
  attributes:
    value: |
      **Welcome!**
     
      This issue tracker is used to track feature requests and bugs.
      You are about to **request a feature** you are missing in XRootD.
     
      Please see below how to report other types of issues.
      - To report a bug, please use the *Bug Report* template.
      - To report a **security vulnerability**, please use https://github.com/xrootd/xrootd/security instead.
      - For general questions about XRootD, or if you just need help with a particular issue,
        please send a message to the mailing list at xrootd-l@slac.stanford.edu
        or open a new [discussion](https://github.com/xrootd/xrootd/discussions) on GitHub.
     
      Thanks for understanding, and for contributing to the project!

- type: textarea
  id: description
  attributes:
    label: Feature Description
    description: |
      Please describe what new functionality you would like to have in XRootD, and what problem it solves for you.
      Have you considered any alternatives or workarounds?
      Do you intend to work towards the implementation of this new feature?
      Which experiment/community is interested in this feature?
  validations:
    required: true
